spring.application.name=p2p-bootcoin-service
server.port=8803
spring.profiles.active=dev

management.endpoints.web.exposure.include=health,info

eureka.instance.instance-id=${spring.application.name}:${server.port}

spring.config.import=optional:configserver:http://localhost:8888
spring.cloud.config.discovery.service-id=config-server-bc
spring.cloud.config.enabled=false



